export const FETCH_ITEMS = 'FETCH_ITEMS';
export const SORT_ITEMS = 'SORT_ITEMS';
export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_TOKEN_ERROR = 'FETCH_TOKEN_ERROR';
export const FETCH_ITEMS_ERROR = 'FETCH_ITEMS_ERROR';